services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: omshah74/dsforge-backend:v1.0
    container_name: ds-forge-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/app/storage:/app/app/storage
      - ./backend/app/db:/app/app/db
    environment:
      - DATABASE_URL=sqlite:///./app/db/ds-forge.sqlite
      - PROJECT_NAME=DS-Forge
    # Overriding the Dockerfile CMD for development hot-reloading
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: omshah74/dsforge-frontend:v1.0
    container_name: ds-forge-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/app:/app/app
      - ./frontend/components:/app/components
      - ./frontend/lib:/app/lib
      - ./frontend/store:/app/store
      - ./frontend/constants:/app/constants
      - ./frontend/public:/app/public
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
